using UnityEngine;

public class Da単oArma : MonoBehaviour
{
    public AudioClip sonidoGolpe;
    private AudioSource audioSource;
    
    public bool puedeHacerDa単o = false; 

    private void Start()
    {
        audioSource = gameObject.AddComponent<AudioSource>();
    }

   private void OnTriggerEnter(Collider other)
    {
        if (puedeHacerDa単o == false) return;

        if (other.CompareTag("Enemigo"))
        {
            VidaEnemigo enemigo = other.GetComponent<VidaEnemigo>();
            if (enemigo != null)
            {
                enemigo.RecibirGolpe();
                if (sonidoGolpe != null) audioSource.PlayOneShot(sonidoGolpe);
                puedeHacerDa単o = false; 
            }
        }
    }
}